name: Tangle code extracted from documentation

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

# Allow one concurrent test
concurrency:
  group: "tangle"
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  tmp:
    runs-on: ubuntu-latest
    steps:
    - name: Download previous tangle
      id: download-previous-tangle
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUN_ID: ${{ github.run_id }}
        REPO: ${{ github.repository }}
        BRANCH: ${{ github.branch }}
      run: |
        API_HEADERS="-H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28'"
        API_PREFIX=repos/$REPO/actions
        # Get Workflow Node ID from Workflow name
        echo API_PREFIX=$API_PREFIX
        echo RUN_ID=$RUN_ID
        # Get Workflow ID from Run ID
        WORKFLOW_ID=$(gh api $API_PREFIX/runs/$RUN_ID -q .workflow_id)
        echo WORKFLOW_ID=$WORKFLOW_ID
        WORKFLOW_NODE_ID=$(gh api $API_PREFIX/workflows/$WORKFLOW_ID -q .node_id)
        echo WORKFLOW_NODE_ID=$WORKFLOW_NODE_ID
        # Get previous Run ID from Workflow ID
        gh api "$API_PREFIX/workflows/$WORKFLOW_ID/runs?status=success&per_page=1&branch=$BRANCH" -q '.workflow_runs[0] | .id'
        PREV_RUN_ID=$(gh api "$API_PREFIX/workflows/$WORKFLOW_ID/runs?status=success&per_page=1&branch=$BRANCH" -q '.workflow_runs[0] | .id')
        echo PREV_RUN_ID=$PREV_RUN_ID
        gh run download $PREV_RUN_ID -R $REPO -n tangled-code -D previous
